import type { FractionData } from "./types/fraction-data";

const DIMENSIONS = {
  WIDTH: 600,
  HEIGHT: 400,
};

const TIME_FRAGMENT = 500; // milliseconds

const PLAYER_CONST: FractionData = {
  MISSILE_SPEED: 35,
  MISSILE_LENGTH: 50,
  MISSILE_OFFSET: 0,

  STRIKE_RADIUS: 0,
  STRIKE_SEGMENTS: 12,
  STRIKE_EXPAND_SPEED: 15,
  STRIKE_MAX_RADIUS: 50,
};

const ENEMY_CONST: FractionData = {
  MISSILE_SPEED: 10,
  MISSILE_LENGTH: 100,
  MISSILE_OFFSET: 0,

  STRIKE_RADIUS: 0,
  STRIKE_SEGMENTS: 14,
  STRIKE_EXPAND_SPEED: 7,
  STRIKE_MAX_RADIUS: 80,
};

export { TIME_FRAGMENT, DIMENSIONS, PLAYER_CONST, ENEMY_CONST };
